basePath: /api
consumes:
- application/json
definitions:
  FooBarRequest:
    properties:
      bar:
        items:
          format: int64
          type: integer
        type: array
        x-go-name: Bar
      foo:
        type: string
        x-go-name: Foo
    title: FooBarRequest represents body of FooBar request.
    type: object
    x-go-package: github.com/pdrum/swagger-automation/api
  FooBarResponse:
    properties:
      baz:
        properties:
          prop:
            type: string
            x-go-name: Prop
        type: object
        x-go-name: Baz
    title: FooBarResponse represents body of FooBar response.
    type: object
    x-go-package: github.com/pdrum/swagger-automation/api
  GameDTO:
    properties:
      board:
        items:
          items:
            $ref: '#/definitions/TileDTO'
          type: array
        type: array
        x-go-name: Board
      columns:
        format: int64
        type: integer
        x-go-name: Columns
      flagAmount:
        format: int64
        type: integer
        x-go-name: FlagAmount
      rows:
        format: int64
        type: integer
        x-go-name: Rows
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  GameRequest:
    properties:
      columns:
        format: int64
        type: integer
        x-go-name: Columns
      mineAmount:
        format: int64
        type: integer
        x-go-name: MineAmount
      rows:
        format: int64
        type: integer
        x-go-name: Rows
    title: 'GameRequest : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  GameResponse:
    properties:
      columns:
        format: int64
        type: integer
        x-go-name: Columns
      mineAmount:
        format: int64
        type: integer
        x-go-name: MineAmount
      rows:
        format: int64
        type: integer
        x-go-name: Rows
    title: 'GameResponse : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  GameSimpleResponse:
    properties:
      gameId:
        format: int64
        type: integer
        x-go-name: GameId
    title: 'GameSimpleResponse : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  MarkRequest:
    properties:
      column:
        format: int64
        type: integer
        x-go-name: Column
      mark:
        type: string
        x-go-name: Mark
      row:
        format: int64
        type: integer
        x-go-name: Row
    title: 'MarkRequest : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  PlayRequest:
    properties:
      column:
        format: int64
        type: integer
        x-go-name: Column
      row:
        format: int64
        type: integer
        x-go-name: Row
    title: 'PlayRequest : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  PlayResponse:
    properties:
      game:
        $ref: '#/definitions/GameDTO'
      stateGame:
        type: string
        x-go-name: StateGame
    title: 'PlayResponse : ...'
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
  TileDTO:
    properties:
      column:
        format: int64
        type: integer
        x-go-name: Column
      mine:
        type: boolean
        x-go-name: Mine
      row:
        format: int64
        type: integer
        x-go-name: Row
      state:
        type: string
        x-go-name: State
      surroundingMineCount:
        format: int64
        type: integer
        x-go-name: SurroundingMineCount
      valueTest:
        format: int64
        type: integer
        x-go-name: ValueTest
    type: object
    x-go-package: minesweeper-API/minesweeper-service/model
host: minesweeper-service-ob.herokuapp.com
info:
  description: The purpose of this API is to provide a Rest Api for game Minesweeper. It is developed in Golang.
  title: Minesweeper-Service.
  version: 1.0.0
paths:
  /foobar:
    post:
      operationId: idOfFoobarEndpoint
      parameters:
      - description: This text will appear as description of your request body.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/FooBarRequest'
      responses:
        "200":
          $ref: '#/responses/foobarResponse'
      summary: Foobar does some amazing stuff.
      tags:
      - foobar-tag
  /games:
    post:
      operationId: createGameEndpoint
      parameters:
      - description: The game's attributes to set.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/GameRequest'
      responses:
        "200":
          $ref: '#/responses/gameSimpleResponseResponse'
        "400":
          $ref: '#/responses/badrequest'
          description: Missing or invalid attributes in body
        "500":
          $ref: '#/responses/internal'
          description: Internal Server Errors
      summary: Create a game.
      tags:
      - games
  /games/{id}:
    get:
      operationId: getGameEndpoint
      parameters:
      - description: The game id
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: GameId
      responses:
        "200":
          $ref: '#/responses/gameResponseResponseWrapper'
        "404":
          $ref: '#/responses/notfound'
          description: Not Found
        "500":
          $ref: '#/responses/internal'
          description: Internal Server Errors
      summary: Play a movement.
      tags:
      - games
  /games/{id}/mark:
    post:
      operationId: markGameEndpoint
      parameters:
      - description: The game's attributes to set.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/MarkRequest'
      - description: The game id
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: GameId
      responses:
        "200":
          $ref: '#/responses/accepted'
        "400":
          $ref: '#/responses/badrequest'
          description: Missing or invalid attributes in body
        "404":
          $ref: '#/responses/notfound'
          description: Not Found
        "500":
          $ref: '#/responses/internal'
          description: Internal Server Errors
      summary: Marka a tile.
      tags:
      - games
  /games/{id}/play:
    post:
      operationId: playGameEndpoint
      parameters:
      - description: The game's attributes to set.
        in: body
        name: Body
        schema:
          $ref: '#/definitions/PlayRequest'
      - description: The game id
        format: int64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: GameId
      responses:
        "200":
          $ref: '#/responses/playResponseResponseWrapper'
        "400":
          $ref: '#/responses/badrequest'
          description: Missing or invalid attributes in body
        "404":
          $ref: '#/responses/notfound'
          description: Not Found
        "500":
          $ref: '#/responses/internal'
          description: Internal Server Errors
      summary: Play a movement.
      tags:
      - games
produces:
- application/json
responses:
  accepted:
    description: accepted response
    schema:
      type: object
  badrequest:
    description: Error BadRequest 400 - Missing or invalid attributes
    schema:
      type: object
  foobarResponse:
    description: This text will appear as description of your response body.
    schema:
      $ref: '#/definitions/FooBarResponse'
  forbidden:
    description: Error Forbidden 403
    schema:
      type: object
  gameResponseResponseWrapper:
    description: ""
    schema:
      $ref: '#/definitions/GameResponse'
  gameSimpleResponseResponse:
    description: ""
    schema:
      $ref: '#/definitions/GameSimpleResponse'
  internal:
    description: Error Internal Server Error 500
    schema:
      type: object
  notfound:
    description: Error NotFaund 404
    schema:
      type: object
  ok:
    description: Success response
    schema:
      type: object
  playResponseResponseWrapper:
    description: ""
    schema:
      $ref: '#/definitions/PlayResponse'
  unauthorized:
    description: Error Unauthorized 401 - Missing Authorization token
    schema:
      type: object
schemes:
- https
securityDefinitions:
  basic:
    type: basic
swagger: "2.0"
